# Sample docker compose for running whtop
services:
  whtop:
    build: .
    ports:
      - "8080:8080"
    environment:
      RUST_LOG: "debug,hyper=info"
      WHTOP_ADDRESS: "0.0.0.0:8080"
      SYSINFO_PROC_PATH: "/host/proc"
    volumes:
      - /proc:/host/proc:ro
