[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.build]
run_task = { name = [
    "build-backend",
    "build-frontend",
], fork = true, parallel = true }

[tasks.run]
run_task = { name = [
    "run-backend",
    "run-frontend",
], fork = true, parallel = true }

[tasks.clean]
run_task = { name = [
    "clean-backend",
    "clean-frontend",
], fork = true, parallel = true }

[tasks.build-frontend]
cwd = "./frontend/whtop_web/"
command = "trunk"
args = ["build"]

[tasks.run-frontend]
cwd = "./frontend/whtop_web/"
command = "trunk"
args = ["serve"]
env = { TRUNK_SERVE_PROXY_BACKEND = "http://localhost:8081/api/" }

[tasks.clean-frontend]
cwd = "./frontend/whtop_web/"
command = "trunk"
args = ["clean"]

[tasks.build-backend]
cwd = "./backend/whtop/"
command = "cargo"
args = ["build", "--bin", "whtop"]

[tasks.run-backend]
cwd = "./backend/whtop/"
command = "cargo"
args = ["run", "--bin", "whtop"]
env = { RUST_LOG = "debug,hyper=info", WHTOP_ADDRESS = "0.0.0.0:8081" }

[tasks.clean-backend]
cwd = "./backend/whtop/"
command = "cargo"
args = ["clean"]

[tasks.build-docker]
command = "docker"
args = ["build", "-t", "whtop", "."]

[tasks.run-docker]
dependencies = ["build-docker"]
command = "docker"
args = [
    "run",
    "--rm",
    "-d",
    "--name",
    "whtop",
    "-v",
    "/proc:/host/proc:ro",
    "-p",
    "8080:8080",
    "-e",
    "RUST_LOG=debug,hyper=info",
    "-e",
    "WHTOP_ADDRESS=0.0.0.0:8080",
    "-e",
    "SYSINFO_PROC_PATH=/host/proc",
    "whtop",
]

[tasks.monitor-docker]
command = "docker"
args = ["logs", "-f", "whtop"]

[tasks.stop-docker]
command = "docker"
args = ["stop", "whtop"]
