task:
  name: rust 1.54 on freebsd 13
  freebsd_instance:
    image: freebsd-13-1-release-amd64
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain=1.54
    - . $HOME/.cargo/env
    - rustup --version
    - rustup component add clippy
  test_script:
    - . $HOME/.cargo/env
    - cargo check
    - cargo check --no-default-features
    - cargo clippy -- -D warnings
    - cargo check --example simple
    - FREEBSD_CI=1 cargo test -j1

task:
  name: rust nightly on freebsd 13
  freebsd_instance:
    image: freebsd-13-1-release-amd64
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain=nightly
    - . $HOME/.cargo/env
    - rustup --version
    - rustup component add clippy
  test_script:
    - . $HOME/.cargo/env
    - cargo check
    - cargo check --no-default-features
    - cargo clippy -- -D warnings
    - cargo check --example simple
    - FREEBSD_CI=1 cargo test -j1
